"""lnurlcash-kit - LNURLcash (LUD-25) bearer notes for Python.

A bearer note is an ordinary LUD-03 withdrawRequest link whose k1 IS the
asset::

    lnurlw://mint.example/w?k1=<spend>&amount=<msat>

Whoever knows the k1 controls the sats behind it, like a banknote. The
``amount`` alongside it is only a claim by whoever encoded the note; the
authoritative value is always ``maxWithdrawable`` from an informational GET.

Every note is a BIP-341 taproot output key ``Q``, named ``cp1<Q>``, and the
k1 is a spend of it: a bearer note's 64-hex preimage, a ``ck1`` signed by
``Q`` for one mint, or a ``cw1`` opening a leaf of ``Q``'s script tree. See
:mod:`lnurlcash_kit.spend` and :mod:`lnurlcash_kit.recoverable`.

Draft spec: https://github.com/lnurl/luds/pull/301

Reference implementations, both by dni and both MIT:
    mint    https://github.com/dni/lnurl-mint
    wallet  https://github.com/dni/lnurl-wallet
"""

from __future__ import annotations

from .bolt11 import decode_bolt11_amount_msat, is_bolt11_invoice, same_invoice
from .client import AsyncLnurlcashClient, LnurlcashClient
from .errors import (
    AmbiguousMint,
    AmbiguousMutation,
    LnurlcashError,
    NotePending,
    NoteSpent,
    NoteUnknown,
    OutputInUse,
    ProtocolError,
    RequestRefused,
    ServiceRejected,
    UnverifiableNote,
    classify_note_error,
    new_secrets_of,
)
from .fees import (
    MintFee,
    apply_mint_fee,
    describe_mint_fee,
    format_fee_percent,
    gross_up_for_mint_fee,
    parse_mint_fee,
)
from .note import (
    build_note_info_url_by_hash,
    build_note_url,
    is_valid_note_input,
    note_declared_amount,
    note_k1,
    note_signature,
    require_note_k1,
    resolve_note_input,
    with_new_k1,
    without_k1,
)
from .protocol import (
    DEFAULT_POLICY,
    MINT_COMMENT_LENGTH,
    InvoiceResult,
    MeltResult,
    MintAddressInfo,
    MutationResult,
    PayRequestInfo,
    Policy,
    RotateResult,
    SplitResult,
    VerifyResult,
    WithdrawRequestInfo,
)
from .cash import (
    CashNode,
    cash_domain_indices,
    cash_node_from_hex,
    cash_node_to_hex,
    derive_cash_child,
    derive_cash_domain_node,
    derive_cash_master,
    derive_cash_root,
)
from .recoverable import (
    NOSTR_CASH_SEED_LABEL,
    Cs1,
    Cx1,
    NoteOwnership,
    Spend,
    SpendKind,
    VerifiedSpend,
    cash_node_to_cx1,
    decode_any_cs1,
    decode_ck1,
    decode_cp1,
    decode_cs1,
    decode_cs1_with_amount,
    decode_cx1,
    decode_spend,
    derive_cash_address_node,
    PURPOSE_CHANGE,
    PURPOSE_LIGHTNING_ADDRESS,
    PURPOSE_WALLET,
    derive_note_pubkey,
    derive_note_secret_key,
    derive_nostr_address_node,
    derive_nostr_cash_seed,
    encode_ck1,
    encode_cp1,
    encode_cs1,
    encode_cs1_with_amount,
    encode_cx1,
    is_any_cs1,
    is_ck1,
    is_cp1,
    is_cs1,
    is_cs1_with_amount,
    is_cx1,
    note_id_of,
    note_lookup_of,
    recover_note_ownership_pubkey,
    sign_note_ownership,
    verify_spend,
)
from .secrets import (
    derive_note_root,
    derive_note_secret,
    generate_note_secret,
    hash_k1,
    is_preimage,
)
from .signature import (
    Certification,
    address_proof_digest,
    address_proof_message,
    note_signature_digest,
    note_signature_digest_for_hash,
    note_signature_message,
    note_signature_message_for_hash,
    sign_address_proof,
    verify_note_signature,
    verify_note_signature_for_key,
    verify_note_signature_hash,
    verify_note_url,
)
from .spend import (
    KEY_PATH_LOCKTIME,
    KEY_PATH_SEQUENCE,
    NUMS_KEY,
    TAPLEAF_VERSION,
    BearerNote,
    Cw1,
    bearer_cw1,
    bearer_leaf,
    bearer_note,
    bearer_note_id,
    check_leaf_policy,
    check_time_claim,
    decode_cw1,
    encode_cw1,
    is_cw1,
    is_x_only_point,
    key_path_sighash,
    output_key_of,
    output_key_of_cw1,
    script_path_sighash,
    spend_domain_of,
    spend_prevout,
    spend_sig_msg,
    tap_leaf_hash,
    taproot_tweak,
)
from .urls import (
    from_bech32_lnurl,
    from_lud17,
    is_allowed_service_url,
    is_bech32_lnurl,
    is_lightning_address,
    lightning_address_username,
    mint_address_url,
    resolve_lnurl_input,
    resolve_mint_input,
    server_of,
    to_bech32_lnurl,
    to_lud17w,
)

__version__ = "0.1.0"

__all__ = [
    "AsyncLnurlcashClient",
    "LnurlcashClient",
    "AmbiguousMint",
    "AmbiguousMutation",
    "DEFAULT_POLICY",
    "LnurlcashError",
    "NotePending",
    "NoteSpent",
    "NoteUnknown",
    "OutputInUse",
    "Policy",
    "ProtocolError",
    "RequestRefused",
    "ServiceRejected",
    "classify_note_error",
    "MintFee",
    "apply_mint_fee",
    "describe_mint_fee",
    "format_fee_percent",
    "gross_up_for_mint_fee",
    "parse_mint_fee",
    "build_note_info_url_by_hash",
    "build_note_url",
    "is_valid_note_input",
    "note_declared_amount",
    "note_k1",
    "note_signature",
    "require_note_k1",
    "resolve_note_input",
    "with_new_k1",
    "without_k1",
    "InvoiceResult",
    "MeltResult",
    "MintAddressInfo",
    "MutationResult",
    "MINT_COMMENT_LENGTH",
    "PayRequestInfo",
    "RotateResult",
    "SplitResult",
    "VerifyResult",
    "UnverifiableNote",
    "WithdrawRequestInfo",
    "new_secrets_of",
    "generate_note_secret",
    "hash_k1",
    "is_preimage",
    "CashNode",
    "cash_domain_indices",
    "cash_node_from_hex",
    "cash_node_to_hex",
    "derive_cash_child",
    "derive_cash_domain_node",
    "derive_cash_master",
    "derive_cash_root",
    "derive_note_root",
    "derive_note_secret",
    "NOSTR_CASH_SEED_LABEL",
    "Cs1",
    "Cx1",
    "NoteOwnership",
    "Spend",
    "SpendKind",
    "VerifiedSpend",
    "cash_node_to_cx1",
    "decode_any_cs1",
    "decode_ck1",
    "decode_cp1",
    "decode_cs1",
    "decode_cs1_with_amount",
    "decode_cx1",
    "decode_spend",
    "derive_cash_address_node",
    "PURPOSE_CHANGE",
    "PURPOSE_LIGHTNING_ADDRESS",
    "PURPOSE_WALLET",
    "derive_note_pubkey",
    "derive_note_secret_key",
    "derive_nostr_address_node",
    "derive_nostr_cash_seed",
    "encode_ck1",
    "encode_cp1",
    "encode_cs1",
    "encode_cs1_with_amount",
    "encode_cx1",
    "is_any_cs1",
    "is_ck1",
    "is_cp1",
    "is_cs1",
    "is_cs1_with_amount",
    "is_cx1",
    "note_id_of",
    "note_lookup_of",
    "recover_note_ownership_pubkey",
    "sign_note_ownership",
    "verify_spend",
    "Certification",
    "address_proof_digest",
    "address_proof_message",
    "note_signature_digest",
    "note_signature_digest_for_hash",
    "note_signature_message",
    "note_signature_message_for_hash",
    "sign_address_proof",
    "verify_note_signature",
    "verify_note_signature_for_key",
    "verify_note_signature_hash",
    "verify_note_url",
    "KEY_PATH_LOCKTIME",
    "KEY_PATH_SEQUENCE",
    "NUMS_KEY",
    "TAPLEAF_VERSION",
    "BearerNote",
    "Cw1",
    "bearer_cw1",
    "bearer_leaf",
    "bearer_note",
    "bearer_note_id",
    "check_leaf_policy",
    "check_time_claim",
    "decode_cw1",
    "encode_cw1",
    "is_cw1",
    "is_x_only_point",
    "key_path_sighash",
    "output_key_of",
    "output_key_of_cw1",
    "script_path_sighash",
    "spend_domain_of",
    "spend_prevout",
    "spend_sig_msg",
    "tap_leaf_hash",
    "taproot_tweak",
    "decode_bolt11_amount_msat",
    "is_bolt11_invoice",
    "same_invoice",
    "from_bech32_lnurl",
    "from_lud17",
    "is_allowed_service_url",
    "is_bech32_lnurl",
    "is_lightning_address",
    "lightning_address_username",
    "mint_address_url",
    "resolve_lnurl_input",
    "resolve_mint_input",
    "server_of",
    "to_bech32_lnurl",
    "to_lud17w",
    "__version__",
]
